### ISSUE TITLE
Discussion of Scala 3 and beyond

### ISSUE THREAD

**Issue by seratch** [scalikejdbc/scalikejdbc#1068]
Scala team announced their great roadmap to Scala version 3. https://www.scala-lang.org/2019/12/18/road-to-scala-3.html

I believe it's about time to talk about the possibilities we can cater to the existing users in Scala 3 and beyond. I have the following topics here.

* Macros incompatibility issues in Scala 3
* My motivation towards Scala 3
* Decision time for Scala 3
* Continuing Scala 2 maintenance

## Macros incompatibility issues in Scala 3

According to https://www.scala-lang.org/2019/12/18/road-to-scala-3.html#what-about-macros

>What about macros?
>
>While Scala 3 can generally consume libraries built with Scala 2.13, this does not work for macros. Macro methods defined in 2.13 libraries cannot be used in Scala 3, because the Scala 3 compiler cannot execute the macro at compile-time.
>
>The macro system from Scala 2 is deeply tied to the internals of the Scala 2 compiler and cannot be migrated in a compatible fashion to Scala 3. Instead, Scala 3 ships with a new macro system. This means that macro definitions have to be re-written when migrating a codebase to Scala 3. Cross-building is possible by having separate source files for Scala 2 and 3 macro definitions.
>
>Libraries that define macros can be made available for both Scala 2.13 and Scala 3 by cross-compiling.

So, Scala 3's macro system is not compatible. I have to say it's challenging for this project. Particularly, [SQLInterpolationMacro](https://github.com/scalikejdbc/scalikejdbc/blob/3.4.0/scalikejdbc-interpolation-macro/src/main/scala/scalikejdbc/SQLInterpolationMacro.scala) is the most valuable piece of this library. I don't think people will still see the benefits of using ScalikeJDBC if without the feature.

In my understanding, offering the exact same functionalities in Scala 3 is almost impossible. If someone has ideas or alternatives that may be acceptable for many, I would love to hear those.

If we find some ways to continue supporting both Scala 2 and 3, I will continue this project for sure! Otherwise, I hate to say this but, if we cannot be with Scala 3 with good quality, we may have to announce that ScalikeJDBC won't support Scala 3 and will continue maintenance releases only for Scala 2.x.

## My motivation towards Scala 3

I'm a bit concerned about the number of reachable developers in the Scala 3 world. Generally speaking, the transition to something incompatible is always hard and it tends to take a long time.

To me, this project is a completely voluntary work. I have a full-time job, other open-source projects, and time with my family. My time is limited.

The possible outcomes will depend on my subjective observation. For now, I'm not so convinced to dedicate my time to Scala 3 related works yet. Depending on circumstances, I may consider looking for future maintainers even if this project continues.

## Decision time for Scala 3

I don't think many of Scala 2 users can move to Scala 3 so quickly. It may take a long time (or never happens to some). 

Even if this project cannot come up with something for Scala 3 at the moment, it doesn't mean we immediately have to make decisions like giving up supporting Scala 3.

## Continuing Scala 2 maintenance

The only certainty at this point is that ScalikeJDBC will continue Scala 2.x maintenance releases for a while. 

I don't guarantee concrete figures here but I will be committing to Scala 2 at least for a few years from now on.

## My ❤️ to the community

Thank you for reading this to the end. Although this project is facing difficulties, I hope the Scala community will have a bright future also with version 3.

**Comment by xuwei-k** [comment]
- https://github.com/xuwei-k/scalikejdbc/commit/8993cdc35a3b0c537bae20b961be185f8dd7ff5d
- https://travis-ci.org/xuwei-k/scalikejdbc/jobs/627060546

**Comment by tototoshi** [comment]
The macros are only used for QueryDSL, right? scalikejdbc is a library that is useful enough without QueryDSL, so even if you can't maintain the functionality of QueryDSL, I would like to continue with other parts.

**Comment by seratch** [comment]
@xuwei-k 
Thanks for sharing the results of their experiments. I hope we can find some ways to make it compatible with the new compiler.

@tototoshi 
Your idea is definitely an option. But I hesitate to provide the ones with limited functionalities under the same brand names. If we continue only `scalikejdbc-core` or similar for Scala 3, I may prefer giving another name for it.

**Comment by seratch** [comment]
cc @kmizu (just because you told me you may be interested in doing some research on this)

Regarding TODOs for Scala 3 (Dotty), I haven't dived into details yet but probably we have three major features to write and maintain another implementation for Scala 3.

1. Rewrite the macro (we're really not sure about the feasibility yet)
1. Rewrite package objects (it looks relatively easy)
1. Rewrite the extended string interpolation? (it's no so difficult, probably?)

## 1. macros

Scala 2 style macros is going to be dropped in Scala 3. https://dotty.epfl.ch/docs/reference/dropped-features/macros.html

```bash
$ find . -name *.scala | xargs grep scala.reflect.macros
./scalikejdbc-syntax-support-macro/src/main/scala/scalikejdbc/autoNamedValues.scala:import scala.reflect.macros.blackbox.Context
./scalikejdbc-syntax-support-macro/src/main/scala/scalikejdbc/autoConstruct.scala:import scala.reflect.macros.blackbox.Context
./scalikejdbc-syntax-support-macro/src/main/scala/scalikejdbc/EntityUtil.scala:import scala.reflect.macros.blackbox.Context
./scalikejdbc-syntax-support-macro/src/main/scala/scalikejdbc/autoColumns.scala:import scala.reflect.macros.blackbox.Context
./scalikejdbc-syntax-support-macro/src/main/scala/scalikejdbc/SQLSyntaxSupportFactory.scala:import scala.reflect.macros.blackbox.Context
./scalikejdbc-interpolation-macro/src/main/scala/scalikejdbc/SQLInterpolationMacro.scala:import scala.reflect.macros.blackbox.Context
```

## 2. package objects

ScalikeJDBC uses package objects mainly for providing convenient wildcard imports.

```bash
$ find . -name package.scala
./scalikejdbc-library/src/main/scala/scalikejdbc/package.scala
./scalikejdbc-mapper-generator/src/main/scala/scalikejdbc/mapper/package.scala
./scalikejdbc-streams/src/main/scala/scalikejdbc/streams/package.scala
./scalikejdbc-core/src/main/scala/scalikejdbc/jsr310/package.scala
```

## 3. string interpolation

I'm really not sure about what to do but according to the build failures, it seems the current code doesn't work in Scala 3.

```
[error]    |value sqls is not a member of StringContext - did you mean StringContext.s?
[error] -- [E008] Member Not Found Error: /home/travis/build/xuwei-k/scalikejdbc/scalikejdbc-core/src/main/scala/scalikejdbc/interpolation/SQLSyntax.scala:50:38 
[error] 50 |  def limit(n: Int): SQLSyntax = sqls"${this} limit ${SQLSyntax(n.toString)}"
[error]    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Correct me if I'm wrong or overlooked something worth to mention. Thoughts?

**Comment by seratch** [comment]
We had a chat with @xuwei-k and @kmizu on Twitter. According to @xuwei-k, the compilation errors on string interpolation seem just the results of other compilation errors. Also, a wonderful thing I should mention here is that he already managed to compile the core library (macros are not included) with Dotty! 

Here are a few findings shared by him:

* ScalaTest hasn't offerred any supports for Dotty yet although they're working on it
* Overriding `val` with `lazy val` is no longer allowed
* For some cases, omitting to have `()` when calling methods is not allowed

Also, Dotty is still in development and the team may need a bit more time for quality assurance. We're open to **Draft** pull requests at any time (and that's greatly helpful for all!) but I'd like to hold off merging breaking changes until the timing we see 3.0.0 milestone releases.

**Comment by seratch** [comment]
I haven't read in details yet but this awesome post may be helpful for the folks that are interested in working on this issue (in the future?). https://contributors.scala-lang.org/t/quill-dotty-update/4080

**Comment by xuwei-k** [comment]
https://github.com/scalikejdbc/scalikejdbc/commit/85c049d41f19efc09d4a2aa09b2a7aaf5e5eea85

**Comment by seratch** [comment]
It seems Scala 3 RC versions may be coming soon. https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html

Thanks to @xuwei-k's dedication, many of the sub projects compile with Scala 3.0.0-M3. Thank you very much for your incredible work for a long time!

Once RC versions are available, we may want to publish as many packages as possible towards the major version. Although we are unable to publish the following packages for Scala 3 users, we can for the rest.

* scalikejdbc-syntax-support-macro
* scalikejdbc-interporation-macro

In regard to the release versions, we will use 4.0.0-M{n}, then 4.0.0-RC{n}. 

>Your idea is definitely an option. But I hesitate to provide the ones with limited functionalities under the same brand names. If we continue only scalikejdbc-core or similar for Scala 3, I may prefer giving another name for it.

Back in 2019, I said I am reluctant to provide limited packages. Now I have changed my mind. Although we may not be able to include macros in the 4.0.x series, it does not mean that we will stop maintaining macros. I'd call it as a "transition period".

@xuwei-k Let me know if there is something we need to resolve before publishing the packages. Also, if you have the bandwidth to publish 4.0.0 milestone versions in a timely manner, I'd appreciate it. Otherwise, I am happy to do the operations (my response can be delayed though).

**Comment by seratch** [comment]
Now that most modules compile with Scala 3.0.0-RC1, we can start planning to release a new version for Scala 3 early adapters! https://github.com/scalikejdbc/scalikejdbc/commit/11c3847f40c70f16c86aaf326e9e08b87f45719b

**Comment by seratch** [comment]
If there is no concern about releasing 4.0.0-M1, I can work on the release soon.

**Comment by timzaak** [comment]
try to rewrite `SelectDynamicMacro[A]`. 

The Macro:
```scala
class SQLSyntax(val value:String, val rawParameters:Seq[Any] = Vector()) {
  override def toString():String = s"SQLSyntax(value: $value), parameters ${rawParameters}"
}

trait SelectDynamicMacro {
  def field(name:String): SQLSyntax
  
  inline def select[E](ref: SelectDynamicMacro, inline name: String): SQLSyntax = ${selectImpl[E]('ref, 'name)}
  
}
def selectImpl[E](ref: Expr[SelectDynamicMacro], name: Expr[String])(using t: Type[E])(using quotes: Quotes): Expr[SQLSyntax] = {
  import quotes.reflect.*

  val typeSymbol = TypeRepr.of[E].typeSymbol
  val expectedNames = typeSymbol.caseFields.map(_.name)
  name.value.foreach { n =>
    if (expectedNames.nonEmpty && !expectedNames.contains(n)) {
      report.error(s"${typeSymbol.fullName}", name.asTerm.pos)
    }
  }
  '{$ref.field($name)}
}
```

```scala
import scala.language.dynamics

trait SQLSyntaxProvider[A] extends Dynamic with SelectDynamicMacro {
  override  def field(name:String):SQLSyntax = {
    SQLSyntax(name)
  }
  inline def selectDynamic(inline name: String): SQLSyntax = select[A](this,name)
}

object Dao extends SQLSyntaxProvider[AA]
object Main {
  def main(args: Array[String]): Unit = {
    println(Dao.a)
  }
}

```

But it's not compatible for Scala2

**Comment by xuwei-k** [comment]
Thanks @timzaak 

https://github.com/scalikejdbc/scalikejdbc/commit/4c533992d02e0e27ec2d82bc381647d765bc22d8

**Comment by seratch** [comment]
@timzaak Thank you very much for providing the code 👍 The last missing piece is scalikejdbc-syntax-support-macro!

**Comment by timzaak** [comment]
I failed when create new case class instance during Macro,
It may be this issue: https://github.com/lampepfl/dotty/issues/11628#issue-823631155
would try it until Scala-RC2 release.
The failed code:
```
trait TypeBinder[T] {
  def apply(columnLabel:String):T
}

given intTypeBinder:TypeBinder[Int] = new TypeBinder[Int] {
  override def apply(columnLabel: String): Int = 1
}

given strTypeBinder:TypeBinder[String] = new TypeBinder[String] {
  override def apply(columnLabel: String): String = columnLabel
}

inline def createCaseClass[T](inline a:T):T = ${createCaseClassImpl[T]}

def createCaseClassImpl[T]()(using quotes:Quotes)(using t:Type[T]): Expr[T] = {
  import quotes.reflect._
  val params = TypeTree.of[T].symbol.caseFields.map{ field =>
    val ValDef(name, typeTree, _) =field.tree
    // it works for scala-M2,  https://github.com/YuriyMazepin/dotty-macro-examples/blob/master/macroTypeclassDerivation/src/macro.scala 
    // but fail in scala-RC1
    val typeBinderTerm: Term = Implicits.search(TypeRepr.of[TypeBinder].appliedTo(typeTree.tpe)) match {
      case res:ImplicitSearchSuccess => res.tree
      case _ => report.throwError(s"cound not find implicit of TypeBinder[${typeTree.tpe}]")
    }
    val v = Apply(Select.unique(typeBinderTerm, "apply"), Expr(name).asTerm::Nil)
    NamedArg(name, v)
  }
  Apply(Select.unique(New(TypeTree.of[T]), "<init>"), params).asExprOf[T]
}
```

**Comment by timzaak** [comment]
Macro:
```scala
import java.sql.ResultSet
import scala.quoted._
import scala.compiletime._
// ---- mock start, should delete

trait SQLSyntaxSupport[A] {
  def useSnakeCaseColumnName:Boolean = true
  def nameConverters: Map[String, String] = Map()
}
trait SQLSyntaxSupportImpl[A] extends SQLSyntaxSupport[A] {
  def  tableName:String
  def columns:Seq[String]
  def apply(rn: scalikejdbc.ResultName[A], rs: scalikejdbc.WrappedResultSet):A

}


trait TypeBinder[+T] {
  def apply(rs:ResultSet ,columnLabel:String):T
}

object scalikejdbc {
  class ResultName[T] {
    def field(name:String):String = name
  }
  
  case class WrappedResultSet(underlying: ResultSet) {
    def get[T](name:String)(using t:TypeBinder[T]): T = t.apply(underlying, name)
  }

  object autoColumns{
    def camelToSnake(fieldName: String, nameConverters: Map[String, String], useSnakeCase: Boolean): String = {
      s"camelToSnakeInAutoColumn{$fieldName}"
    }
  }
  
  object SQLSyntaxSupportFactory {
    def camelToSnake(str:String) = s"camelToSnakeInFactory{$str}"
  }
}

// ---- mock end


inline def apply[A](inline excludes:String*):SQLSyntaxSupportImpl[A] = ${apply_impl[A]('excludes)}

inline def debug[A](inline excludes:String*):SQLSyntaxSupportImpl[A] = ${debug_impl[A]('excludes)}


def apply_impl[A](excludes:Expr[Seq[String]])(using quotes:Quotes)(using t:Type[A]):Expr[SQLSyntaxSupportImpl[A]] = {
  import quotes.reflect._
  val tpeSym = TypeTree.of[A].symbol
  val tpeRepr = TypeTree.of[A]
  val excludeNames:Expr[List[String]] = Expr.ofList(excludes match {
    case Varargs(expr) if (expr.exists(_.value.isEmpty)) =>
      report.throwError(s"You must use String literal values for field names to exclude from case class ${tpeSym.fullName}", excludes.asTerm.pos)
    case Varargs(expr) =>
      expr
  })
  
  if(tpeSym.flags.is(Flags.Case)) {
    val fields = tpeSym.caseFields.map {f =>
      val ValDef(name, typeTree, _) = f.tree
      (name, typeTree)
    }
    '{
      new SQLSyntaxSupportImpl[A] {
        
        lazy val tableName:String = scalikejdbc.SQLSyntaxSupportFactory.camelToSnake(${Expr(tpeSym.name)})
        
        lazy val columns:Seq[String] = ${excludeNames}.map(v => scalikejdbc.autoColumns.camelToSnake(v,nameConverters, useSnakeCaseColumnName))
        
        def apply(rn: scalikejdbc.ResultName[A], rs: scalikejdbc.WrappedResultSet):A = {
          ${
            Apply(Select.unique(New(TypeTree.of[A]), "<init>"), fields.map{case (name, typeTree) => {
              val t = TypeRepr.of[TypeBinder].appliedTo(typeTree.tpe).asType
              val typeBinder = t match {
                case '[a] => '{summonInline[a]}
              }
              val exprs = typeTree.tpe.asType match {
                case '[b] => '{rs.get[b](rn.field(${Expr(name)}))(using ${typeBinder.asInstanceOf[Expr[TypeBinder[b]]]})}
              }
              NamedArg(name, exprs.asTerm)
            }}).asExprOf[A]
          }
        }
      }
    }
  } else {
    report.throwError(s"${tpeSym.fullName} is not case class")
  }
}

def debug_impl[A](excludes:Expr[Seq[String]])(using quotes:Quotes)(using t:Type[A]):Expr[SQLSyntaxSupportImpl[A]] = {
  val expr = apply_impl[A](excludes)
  println(expr.show)
  expr
}
```
The Test code:
```scala
import java.sql.ResultSet

case class AA(a:Int, b:String)

object Main {
  def main(args: Array[String]): Unit = {

    given intTypeBinder:TypeBinder[Int] = new TypeBinder[Int] {
      override def apply(rs:ResultSet, columnLabel: String): Int = 123
    }

    given strTypeBinder:TypeBinder[String] = new TypeBinder[String] {
      override def apply(rs:ResultSet,columnLabel: String): String = columnLabel
    }
    //println(debug[AA]())
    val result = apply[AA]("ss")
    println(result.tableName)
    println(result.columns)
    println(result.apply(new scalikejdbc.ResultName[AA](),scalikejdbc.WrappedResultSet(null)))
    }
}
```

This only support  normal case class.

**Comment by xuwei-k** [comment]
https://github.com/scalikejdbc/scalikejdbc/commit/833501983b75e27d2861456630a46aa026c8e448

**Comment by seratch** [comment]
We've released version 4.0.0-RC1, which is compatible with Scala 2.12, 2.13, aaaaaaaand **S C A L A 3**!!!! 🎉 We will wait for feedback from the community for a while. If everything goes well, we will release v4.0.0 final by the end of this month.

https://github.com/scalikejdbc/scalikejdbc/blob/master/notes/4.0.0.markdown

Thanks a lot for all the contributors 🙌

**Comment by seratch** [comment]
I'm sorry for a bit delay of v4.0.0 final release! If possible, I wanted to have https://github.com/scalikejdbc/scalikejdbc/pull/1249 in v4.0 but it seems that Scala 3 is not fully compatible with Scala 2.13 for this module. If anyone is interested in working on the module together, your help would be appreciated.

I'm going to do 4.0.0 release today.

**Comment by seratch** [comment]
Version 4.0.0 was released. Thanks a lot for the time and efforts by all the contributors for the release 🚀
