### ISSUE TITLE
Version 2.2.8 breaks code using batch.apply

### ISSUE THREAD

**Issue by jokade** [scalikejdbc/scalikejdbc#489]
The changes to the return type of `SQLBatch.apply` introduced in #428 break my code using batch updates. I'm using Scala 2.11.7 and get the compiler error message:
```
Cannot construct a collection of type Nothing with elements of type Int based on a collection of type Nothing.
```
My code compiles up to scalikejdbc version 2.2.7. If I need an explicit type hint, could you please tell me where to place it?

**Comment by seratch** [comment]
Can you show us an example code which gets the compilation error since 2.2.8?

**Comment by jokade** [comment]
Sure, here's an example:

```scala
﻿DB autoCommit { implicit session =>
    /* ... */
    val filtered = assessments.filter(a => a.theoretical>0 || a.practical>0 )
    sql"""INSERT INTO wilma.knowledge(pid,cid,theoretical,practical) VALUES (?,?,?,?)"""
      .batch(filtered.toSeq.map(a => Seq(pid,a.cid,a.theoretical,a.practical)):_*)
      .apply  // <-- fails with type error during compilation for >=2.2.8

    /* ... */
  }
```

**Comment by seratch** [comment]
@jokade I've tried for a while but couldn't reproduce your situation. In most cases, #428 should not bring API incompatibility to existing code. If you have time, please share us a minimum example which reproduces your situation.

**Comment by seratch** [comment]
@lantian0802 4 months have passed. We've not figured out any actions needed yet. Can I close this issue now?

**Comment by jokade** [comment]
Yes, sorry; I'm still using the old version and had no time to investigate further, thanks.
